#!/bin/csh -f 

# Run IDL-Python bridge setup
# Optimized for Anaconda/Python 2.7 and IDL 8.5.
# Make sure to define or hardwire $PYTHONHOME and $IDL_DIR beforehand to your local setup.
# Run as "sudo csh pyidl_setup"

# Zarro (ADNET) 10-13-17 

set CWD = `pwd` 
onintr catch

setenv IDL_DIR /usr/local/exelis/idl85
setenv PYTHONHOME /usr
setenv PYTHONPATH $IDL_DIR/lib/bridges 

cd $IDL_DIR/lib/bridges
$PYTHONHOME/bin/python setup.py install   

catch:
if ($?CWD) then  
 cd $CWD 
endif
